[SQUASH] KernelSU: Fixup selinux for compile
../drivers/kernelsu/selinux/sepolicy.c:802:43: error: no member named 'total_nr_elements' in 'struct ebitmap'
        for (j = 0; j < db->type_attr_map_array->total_nr_elements; j++) {
                        ~~~~~~~~~~~~~~~~~~~~~~~  ^
../drivers/kernelsu/selinux/sepolicy.c:809:46: error: member reference base type 'struct type_datum *' is not a structure or union
        for (j = 0; j < db->type_val_to_struct_array->total_nr_elements; j++) {
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^ ~~~~~~~~~~~~~~~~~
../drivers/kernelsu/selinux/sepolicy.c:828:9: error: incompatible pointer types assigning to 'struct flex_array *' from 'struct ebitmap *' [-Werror,-Wincompatible-pointer-types]
        old_fa = db->type_attr_map_array;
               ^ ~~~~~~~~~~~~~~~~~~~~~~~
../drivers/kernelsu/selinux/sepolicy.c:829:26: error: incompatible pointer types assigning to 'struct ebitmap *' from 'struct flex_array *' [-Werror,-Wincompatible-pointer-types]
        db->type_attr_map_array = new_type_attr_map_array;
                                ^ ~~~~~~~~~~~~~~~~~~~~~~~
../drivers/kernelsu/selinux/sepolicy.c:838:9: error: incompatible pointer types assigning to 'struct flex_array *' from 'struct type_datum **' [-Werror,-Wincompatible-pointer-types]
        old_fa = db->type_val_to_struct_array;
               ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../drivers/kernelsu/selinux/sepolicy.c:839:31: error: incompatible pointer types assigning to 'struct type_datum **' from 'struct flex_array *' [-Werror,-Wincompatible-pointer-types]
        db->type_val_to_struct_array = new_type_val_to_struct;
                                     ^ ~~~~~~~~~~~~~~~~~~~~~~
../drivers/kernelsu/selinux/sepolicy.c:846:9: error: incompatible pointer types assigning to 'struct flex_array *' from 'char **' [-Werror,-Wincompatible-pointer-types]
        old_fa = db->sym_val_to_name[SYM_TYPES];
               ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../drivers/kernelsu/selinux/sepolicy.c:847:33: error: incompatible pointer types assigning to 'char **' from 'struct flex_array *' [-Werror,-Wincompatible-pointer-types]
        db->sym_val_to_name[SYM_TYPES] = new_val_to_name_types;
                                       ^ ~~~~~~~~~~~~~~~~~~~~~
8 errors generated.

Revert 'BACKPORT: FROMGIT: [PATCH] selinux: fix handling of uninitialized selinux state in'
This reverts commit ed436f4.
Revert 'BACKPORT: FROMGIT: selinux: convert to kvmalloc'
This reverts commit ee9d254.

Signed-off-by: onettboots <blackcocopet@gmail.com>
(cherry picked from commit 517a6667d2f74286cf260c8adf918fd905d667f4)